---
- name: Download helm 
  command: "curl -fsSL -o /tmp/get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3"

- name: Install 
  command: "bash /tmp/get_helm.sh"

- name: Add repo
  command: "/usr/local/bin/helm repo add {{ item.name }} {{ item.url }}"
  with_items:
    - "{{ helm_charts }}"
  become: true

- name:  Update repo
  command: "/usr/local/bin/helm repo update"
  become: true

- name:  Namespace creation
  command: "/usr/bin/kubectl create namespace {{ item }}"
  with_items:
    - "{{ namespaces }}"    
  become: true

- name: Install Prod Apps
  command: "/usr/local/bin/helm install {{ item.name }} {{ item.chart_name }} -n prd"
  with_items:
   - "{{ prod_apps }}"
  become: true 

- name: Install Dev Apps
  command: "/usr/local/bin/helm install {{ item.name }} {{ item.chart_name }} -n dev"
  with_items:
   - "{{ dev_apps }}"
  become: true 
