- name: enable firewall services 
  command: "/usr/bin/firewall-cmd --permanent --add-port={{ item }}"
  with_items: 
    - "{{ firewall_nodes_ports }}" 
  become: yes

- name: firewall reload 
  command: "/usr/bin/firewall-cmd --reload"
  become: yes