- name: enable firewall services 
  command: "/usr/bin/firewall-cmd --permanent --add-port={{ item }}"
  with_items: 
    - "{{ firewall_master_ports }}" 
  become: yes

- name: firewall allow access from worker 
  command: "firewall-cmd --permanent --add-rich-rule '{{item}}'"
  with_items: 
    - ['rule family=ipv4 source address=192.168.1.11/32 accept', 'rule family=ipv4 source address=192.168.1.12/32 accept']
  become: yes

- name: firewall reload 
  command: "/usr/bin/firewall-cmd --zone=public --permanent --add-rich-rule 'rule family=ipv4 source address=172.17.0.0/16 accept'"
  become: yes

- name: firewall reload 
  command: "/usr/bin/firewall-cmd --reload"
  become: yes