---
- name: Add kubeadmin
  user:
    name: kubeadmin
    shell: /bin/bash
    create_home: True
    append: yes
  become : true

- name: Set sudoers
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/kubeadmin
  become : true

- name: Create kubeadmin home
  file:
    path: /home/kubeadmin/.kube
    state: directory
  become: yes

- name: Set kubeadmin pwd
  authorized_key:
    user: kubeadmin
    state: present
    manage_dir: yes
    key: "{{  public_key }}"
  become: true 

- name:  Copy kubeconfig
  command: "/usr/bin/cp -f  /etc/kubernetes/admin.conf /home/kubeadmin/.kube/config"
  become: yes

- name : Set permissions
  file:
   path: /home/kubeadmin/.kube/config
   owner: kubeadmin
  become: yes